# Workflow to publish to NPM.

# It starts automatically when a new Github Release is published
# or the draft is changed to a public version.
# It will not start for drafts.

# Automatically detects if there should be a latest or beta version.
# When a Github Release is marked as a Pre-release it will publish to NPM as beta.

# Get version from the Github Release tag. 
# For latest version it should be like: 1.2.3 , 1.2.4 , 1.3.0 , etc.
# For beta version it should be like: 1.2.3-beta.0 , 1.2.3-beta.1 , 1.2.3-beta.2 , etc.

# Github Release description for Pre-releases (beta) is not required.



name: Create and publish latest / beta release

on:
  release:
    types: [published]

jobs:
  create-release:
    
    name: Create latest / beta release
    runs-on: ubuntu-latest

    steps:

      #Summary
      - name: Summary
        run: |
          echo "The release version will be: ${{ github.event.release.tag_name }}"
      
      # Chech out repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "82271669+mkz212@users.noreply.github.com"
          git config --global user.name "GitHub Actions Test"

      # Install dependencies and build
      - name: Install dependencies and build ðŸ”§
        run: npm ci && npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Upgrade version
      - name: Upgrade version â¬†
        run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish Latest
      - name: Publish package on NPM - LATEST ðŸ“¦
        if: "!github.event.release.prerelease"
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish beta
      - name: Publish package on NPM - BETA ðŸ“¦
        if: "github.event.release.prerelease"
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin && git push --tags

      
      
     

